# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow-2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT
from matplotlib.figure import Figure

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1064, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.infoGB = QtWidgets.QGroupBox(self.centralwidget)
        self.infoGB.setObjectName("infoGB")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoGB)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.infoTab = QtWidgets.QTabWidget(self.infoGB)
        self.infoTab.setObjectName("infoTab")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.infoTab.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.infoTab.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.infoTab.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.infoTab.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.infoTab)
        self.gridLayout.addWidget(self.infoGB, 0, 1, 1, 1)
        self.mngGB = QtWidgets.QGroupBox(self.centralwidget)
        self.mngGB.setObjectName("mngGB")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mngGB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mngTab = QtWidgets.QTabWidget(self.mngGB)
        self.mngTab.setObjectName("mngTab")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.mngTab.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.mngTab)
        self.gridLayout.addWidget(self.mngGB, 0, 0, 1, 1)
        self.imageGB = QtWidgets.QGroupBox(self.centralwidget)
        self.imageGB.setObjectName("imageGB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.imageGB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        fig = Figure(figsize=(3, 3), dpi=100)
        ax = fig.add_subplot(111)
        self.canvas = FigureCanvasQTAgg(fig)
        self.canvas.setObjectName("canvas")
        toolbar = NavigationToolbar2QT(self.canvas, MainWindow)
        self.verticalLayout_4.addWidget(toolbar)
        self.verticalLayout_4.addWidget(self.canvas)
        ax.plot([0,1,2,3,4], [10,1,20,3,40])
        self.gridLayout.addWidget(self.imageGB, 2, 1, 1, 1)
        self.plotterGB = QtWidgets.QGroupBox(self.centralwidget)
        self.plotterGB.setObjectName("plotterGB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plotterGB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.plotterGB)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.subplotPB = QtWidgets.QPushButton(self.frame)
        self.subplotPB.setMaximumSize(QtCore.QSize(120, 16777215))
        self.subplotPB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.subplotPB.setObjectName("subplotPB")
        self.horizontalLayout_2.addWidget(self.subplotPB)
        self.stylesPB = QtWidgets.QPushButton(self.frame)
        self.stylesPB.setMaximumSize(QtCore.QSize(120, 16777215))
        self.stylesPB.setObjectName("stylesPB")
        self.horizontalLayout_2.addWidget(self.stylesPB)
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.plotPB = QtWidgets.QPushButton(self.frame)
        self.plotPB.setObjectName("plotPB")
        self.horizontalLayout_2.addWidget(self.plotPB)
        self.SavePB = QtWidgets.QPushButton(self.frame)
        self.SavePB.setObjectName("SavePB")
        self.horizontalLayout_2.addWidget(self.SavePB)
        self.verticalLayout_3.addWidget(self.frame)
        self.pltTab = QtWidgets.QTabWidget(self.plotterGB)
        self.pltTab.setObjectName("pltTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pltTab.addTab(self.tab, "")
        self.verticalLayout_3.addWidget(self.pltTab)
        self.gridLayout.addWidget(self.plotterGB, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menuBar.setObjectName("menuBar")
        self.menua = QtWidgets.QMenu(self.menuBar)
        self.menua.setObjectName("menua")
        self.menuOpen_Data = QtWidgets.QMenu(self.menua)
        self.menuOpen_Data.setObjectName("menuOpen_Data")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionb = QtWidgets.QAction(MainWindow)
        self.actionb.setObjectName("actionb")
        self.actiond = QtWidgets.QAction(MainWindow)
        self.actiond.setObjectName("actiond")
        self.actionSave_Method = QtWidgets.QAction(MainWindow)
        self.actionSave_Method.setObjectName("actionSave_Method")
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionSave_Method_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_Method_2.setObjectName("actionSave_Method_2")
        self.actionData = QtWidgets.QAction(MainWindow)
        self.actionData.setObjectName("actionData")
        self.actionMethod = QtWidgets.QAction(MainWindow)
        self.actionMethod.setObjectName("actionMethod")
        self.actionStyle = QtWidgets.QAction(MainWindow)
        self.actionStyle.setObjectName("actionStyle")
        self.menuOpen_Data.addAction(self.actionData)
        self.menuOpen_Data.addAction(self.actionMethod)
        self.menua.addAction(self.menuOpen_Data.menuAction())
        self.menua.addAction(self.actionb)
        self.menua.addSeparator()
        self.menua.addAction(self.actionSave_Image)
        self.menua.addAction(self.actionSave_Method_2)
        self.menuBar.addAction(self.menua.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.infoTab.setCurrentIndex(0)
        self.mngTab.setCurrentIndex(0)
        self.pltTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infoGB.setTitle(_translate("MainWindow", "Info"))
        self.infoTab.setTabText(self.infoTab.indexOf(self.tab_7), _translate("MainWindow", "Raw Data"))
        self.infoTab.setTabText(self.infoTab.indexOf(self.tab_8), _translate("MainWindow", "Data"))
        self.infoTab.setTabText(self.infoTab.indexOf(self.tab_4), _translate("MainWindow", "Variables"))
        self.infoTab.setTabText(self.infoTab.indexOf(self.tab_3), _translate("MainWindow", "Plot Data"))
        self.mngGB.setTitle(_translate("MainWindow", "Data Managers"))
        self.mngTab.setTabText(self.mngTab.indexOf(self.tab_5), _translate("MainWindow", "New Manager"))
        self.imageGB.setTitle(_translate("MainWindow", "Image Preview"))
        self.plotterGB.setTitle(_translate("MainWindow", "Plotter"))
        self.subplotPB.setText(_translate("MainWindow", "Subplot..."))
        self.stylesPB.setText(_translate("MainWindow", "Styles..."))
        self.plotPB.setText(_translate("MainWindow", "Plot"))
        self.SavePB.setText(_translate("MainWindow", "Save"))
        self.pltTab.setTabText(self.pltTab.indexOf(self.tab), _translate("MainWindow", "Subplot 0 Method"))
        self.menua.setTitle(_translate("MainWindow", "File"))
        self.menuOpen_Data.setTitle(_translate("MainWindow", "Open..."))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionb.setText(_translate("MainWindow", "New Method"))
        self.actiond.setText(_translate("MainWindow", "Open Method"))
        self.actionSave_Method.setText(_translate("MainWindow", "Save Method..."))
        self.actionSave_Image.setText(_translate("MainWindow", "Save Image"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.actionSave_Method_2.setText(_translate("MainWindow", "Save Method"))
        self.actionData.setText(_translate("MainWindow", "Data"))
        self.actionMethod.setText(_translate("MainWindow", "Method"))
        self.actionStyle.setText(_translate("MainWindow", "Style"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

