# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1064, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.infoGB = QtWidgets.QGroupBox(self.centralwidget)
        self.infoGB.setObjectName("infoGB")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoGB)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.infoTabs = QtWidgets.QTabWidget(self.infoGB)
        self.infoTabs.setObjectName("infoTabs")
        self.rawDataTab = QtWidgets.QWidget()
        self.rawDataTab.setObjectName("rawDataTab")
        self.infoTabs.addTab(self.rawDataTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.infoTabs.addTab(self.dataTab, "")
        self.varTab = QtWidgets.QWidget()
        self.varTab.setObjectName("varTab")
        self.infoTabs.addTab(self.varTab, "")
        self.plotDataTab = QtWidgets.QWidget()
        self.plotDataTab.setObjectName("plotDataTab")
        self.infoTabs.addTab(self.plotDataTab, "")
        self.verticalLayout_2.addWidget(self.infoTabs)
        self.gridLayout.addWidget(self.infoGB, 0, 1, 1, 1)
        self.mngGB = QtWidgets.QGroupBox(self.centralwidget)
        self.mngGB.setObjectName("mngGB")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mngGB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mngTabs = QtWidgets.QTabWidget(self.mngGB)
        self.mngTabs.setObjectName("mngTabs")
        self.newMngTab = QtWidgets.QWidget()
        self.newMngTab.setObjectName("newMngTab")
        self.mngTabs.addTab(self.newMngTab, "")
        self.verticalLayout.addWidget(self.mngTabs)
        self.gridLayout.addWidget(self.mngGB, 0, 0, 1, 1)
        self.imageGB = QtWidgets.QGroupBox(self.centralwidget)
        self.imageGB.setObjectName("imageGB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.imageGB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.canvas = QtWidgets.QGraphicsView(self.imageGB)
        self.canvas.setObjectName("canvas")
        self.verticalLayout_4.addWidget(self.canvas)
        self.gridLayout.addWidget(self.imageGB, 2, 1, 1, 1)
        self.plotterGB = QtWidgets.QGroupBox(self.centralwidget)
        self.plotterGB.setObjectName("plotterGB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plotterGB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.plotterGB)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.subplotPB = QtWidgets.QPushButton(self.frame)
        self.subplotPB.setMaximumSize(QtCore.QSize(120, 16777215))
        self.subplotPB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.subplotPB.setObjectName("subplotPB")
        self.horizontalLayout_2.addWidget(self.subplotPB)
        self.stylesPB = QtWidgets.QPushButton(self.frame)
        self.stylesPB.setMaximumSize(QtCore.QSize(120, 16777215))
        self.stylesPB.setObjectName("stylesPB")
        self.horizontalLayout_2.addWidget(self.stylesPB)
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.plotPB = QtWidgets.QPushButton(self.frame)
        self.plotPB.setObjectName("plotPB")
        self.horizontalLayout_2.addWidget(self.plotPB)
        self.SavePB = QtWidgets.QPushButton(self.frame)
        self.SavePB.setObjectName("SavePB")
        self.horizontalLayout_2.addWidget(self.SavePB)
        self.verticalLayout_3.addWidget(self.frame)
        self.pltTabs = QtWidgets.QTabWidget(self.plotterGB)
        self.pltTabs.setObjectName("pltTabs")
        self.subplot0tab = QtWidgets.QWidget()
        self.subplot0tab.setObjectName("subplot0tab")
        self.pltTabs.addTab(self.subplot0tab, "")
        self.verticalLayout_3.addWidget(self.pltTabs)
        self.gridLayout.addWidget(self.plotterGB, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menuBar.setObjectName("menuBar")
        self.menua = QtWidgets.QMenu(self.menuBar)
        self.menua.setObjectName("menua")
        self.menuOpenData = QtWidgets.QMenu(self.menua)
        self.menuOpenData.setObjectName("menuOpenData")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.menuNewMethod = QtWidgets.QAction(MainWindow)
        self.menuNewMethod.setObjectName("menuNewMethod")
        self.actiond = QtWidgets.QAction(MainWindow)
        self.actiond.setObjectName("actiond")
        self.actionSave_Method = QtWidgets.QAction(MainWindow)
        self.actionSave_Method.setObjectName("actionSave_Method")
        self.menuSaveImage = QtWidgets.QAction(MainWindow)
        self.menuSaveImage.setObjectName("menuSaveImage")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.menuSaveMethod = QtWidgets.QAction(MainWindow)
        self.menuSaveMethod.setObjectName("menuSaveMethod")
        self.actionData = QtWidgets.QAction(MainWindow)
        self.actionData.setObjectName("actionData")
        self.actionMethod = QtWidgets.QAction(MainWindow)
        self.actionMethod.setObjectName("actionMethod")
        self.actionStyle = QtWidgets.QAction(MainWindow)
        self.actionStyle.setObjectName("actionStyle")
        self.menuOpenData.addAction(self.actionData)
        self.menuOpenData.addAction(self.actionMethod)
        self.menua.addAction(self.menuOpenData.menuAction())
        self.menua.addAction(self.menuNewMethod)
        self.menua.addSeparator()
        self.menua.addAction(self.menuSaveImage)
        self.menua.addAction(self.menuSaveMethod)
        self.menuBar.addAction(self.menua.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.infoTabs.setCurrentIndex(0)
        self.mngTabs.setCurrentIndex(0)
        self.pltTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infoGB.setTitle(_translate("MainWindow", "Info"))
        self.infoTabs.setTabText(self.infoTabs.indexOf(self.rawDataTab), _translate("MainWindow", "Raw Data"))
        self.infoTabs.setTabText(self.infoTabs.indexOf(self.dataTab), _translate("MainWindow", "Data"))
        self.infoTabs.setTabText(self.infoTabs.indexOf(self.varTab), _translate("MainWindow", "Variables"))
        self.infoTabs.setTabText(self.infoTabs.indexOf(self.plotDataTab), _translate("MainWindow", "Plot Data"))
        self.mngGB.setTitle(_translate("MainWindow", "Data Managers"))
        self.mngTabs.setTabText(self.mngTabs.indexOf(self.newMngTab), _translate("MainWindow", "New Manager"))
        self.imageGB.setTitle(_translate("MainWindow", "Image Preview"))
        self.plotterGB.setTitle(_translate("MainWindow", "Plotter"))
        self.subplotPB.setText(_translate("MainWindow", "Subplot..."))
        self.stylesPB.setText(_translate("MainWindow", "Styles..."))
        self.plotPB.setText(_translate("MainWindow", "Plot"))
        self.SavePB.setText(_translate("MainWindow", "Save"))
        self.pltTabs.setTabText(self.pltTabs.indexOf(self.subplot0tab), _translate("MainWindow", "Subplot 0 Method"))
        self.menua.setTitle(_translate("MainWindow", "File"))
        self.menuOpenData.setTitle(_translate("MainWindow", "Open..."))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuNewMethod.setText(_translate("MainWindow", "New Method"))
        self.actiond.setText(_translate("MainWindow", "Open Method"))
        self.actionSave_Method.setText(_translate("MainWindow", "Save Method..."))
        self.menuSaveImage.setText(_translate("MainWindow", "Save Image"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.menuSaveMethod.setText(_translate("MainWindow", "Save Method"))
        self.actionData.setText(_translate("MainWindow", "Data"))
        self.actionMethod.setText(_translate("MainWindow", "Method"))
        self.actionStyle.setText(_translate("MainWindow", "Style"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

