# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mngDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_eventDialog(object):
    def setupUi(self, eventDialog):
        eventDialog.setObjectName("eventDialog")
        eventDialog.resize(444, 274)
        font = QtGui.QFont()
        font.setPointSize(10)
        eventDialog.setFont(font)
        eventDialog.setSizeGripEnabled(False)
        eventDialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(eventDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(eventDialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 2, 1, 2)
        self.rParamBox = QtWidgets.QGroupBox(eventDialog)
        self.rParamBox.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rParamBox.setFont(font)
        self.rParamBox.setObjectName("rParamBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rParamBox)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.rParamBox, 4, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.oParamBox = QtWidgets.QGroupBox(eventDialog)
        self.oParamBox.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.oParamBox.setFont(font)
        self.oParamBox.setObjectName("oParamBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.oParamBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.oParamBox, 5, 0, 1, 4)
        self.actFrm = QtWidgets.QGroupBox(eventDialog)
        self.actFrm.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actFrm.setFont(font)
        self.actFrm.setAutoFillBackground(False)
        self.actFrm.setObjectName("actFrm")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.actFrm)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.actionCB = QtWidgets.QComboBox(self.actFrm)
        self.actionCB.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actionCB.setFont(font)
        self.actionCB.setObjectName("actionCB")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.actionCB.addItem("")
        self.horizontalLayout.addWidget(self.actionCB)
        self.gridLayout.addWidget(self.actFrm, 1, 0, 1, 3)

        self.retranslateUi(eventDialog)
        QtCore.QMetaObject.connectSlotsByName(eventDialog)

    def retranslateUi(self, eventDialog):
        _translate = QtCore.QCoreApplication.translate
        eventDialog.setWindowTitle(_translate("eventDialog", "Dialog"))
        self.rParamBox.setTitle(_translate("eventDialog", "Required Parameters"))
        self.oParamBox.setTitle(_translate("eventDialog", "Optional Parameters"))
        self.actFrm.setTitle(_translate("eventDialog", "Action"))
        self.actionCB.setCurrentText(_translate("eventDialog", "Choose Action"))
        self.actionCB.setItemText(0, _translate("eventDialog", "Choose Action"))
        self.actionCB.setItemText(1, _translate("eventDialog", "Format Raw Data"))
        self.actionCB.setItemText(2, _translate("eventDialog", "Truncate Data"))
        self.actionCB.setItemText(3, _translate("eventDialog", "Set Variable"))
        self.actionCB.setItemText(4, _translate("eventDialog", "Add Plot Data"))
        self.actionCB.setItemText(5, _translate("eventDialog", "Modify Plot Data"))
        self.actionCB.setItemText(6, _translate("eventDialog", "Set Plot Data Range By Value"))
        self.actionCB.setItemText(7, _translate("eventDialog", "Set Plot Data Range By Turn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    eventDialog = QtWidgets.QDialog()
    ui = Ui_eventDialog()
    ui.setupUi(eventDialog)
    eventDialog.show()
    sys.exit(app.exec_())

